// Generated by delombok at Tue Jul 03 21:08:31 NOVT 2018
package org.statesync.model;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;
import java.util.stream.Collectors;
import org.statesync.model.permissions.ItemPermissions;
import org.statesync.model.permissions.ListPermissions;

public class AnnotatedList<Item, IP extends ItemPermissions, LP extends ListPermissions> {
	public List<AnnotatedItem<Item, IP>> data = new ArrayList<>();
	public LP permissions;
	public Pagination pagination = new Pagination();

	public <DT> void setData(final Collection<DT> source, final Function<DT, Item> itemMap, final Function<DT, IP> permissionsMap) {
		this.data = source.stream().map(src -> new AnnotatedItem<>(itemMap.apply(src), permissionsMap.apply(src))).collect(Collectors.toList());
	}

	@java.lang.SuppressWarnings("all")
	public List<AnnotatedItem<Item, IP>> getData() {
		return this.data;
	}

	@java.lang.SuppressWarnings("all")
	public LP getPermissions() {
		return this.permissions;
	}

	@java.lang.SuppressWarnings("all")
	public Pagination getPagination() {
		return this.pagination;
	}

	@java.lang.SuppressWarnings("all")
	public void setData(final List<AnnotatedItem<Item, IP>> data) {
		this.data = data;
	}

	@java.lang.SuppressWarnings("all")
	public void setPermissions(final LP permissions) {
		this.permissions = permissions;
	}

	@java.lang.SuppressWarnings("all")
	public void setPagination(final Pagination pagination) {
		this.pagination = pagination;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof AnnotatedList)) return false;
		final AnnotatedList<?, ?, ?> other = (AnnotatedList<?, ?, ?>) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$data = this.getData();
		final java.lang.Object other$data = other.getData();
		if (this$data == null ? other$data != null : !this$data.equals(other$data)) return false;
		final java.lang.Object this$permissions = this.getPermissions();
		final java.lang.Object other$permissions = other.getPermissions();
		if (this$permissions == null ? other$permissions != null : !this$permissions.equals(other$permissions)) return false;
		final java.lang.Object this$pagination = this.getPagination();
		final java.lang.Object other$pagination = other.getPagination();
		if (this$pagination == null ? other$pagination != null : !this$pagination.equals(other$pagination)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof AnnotatedList;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $data = this.getData();
		result = result * PRIME + ($data == null ? 43 : $data.hashCode());
		final java.lang.Object $permissions = this.getPermissions();
		result = result * PRIME + ($permissions == null ? 43 : $permissions.hashCode());
		final java.lang.Object $pagination = this.getPagination();
		result = result * PRIME + ($pagination == null ? 43 : $pagination.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "AnnotatedList(data=" + this.getData() + ", permissions=" + this.getPermissions() + ", pagination=" + this.getPagination() + ")";
	}

	@java.lang.SuppressWarnings("all")
	public AnnotatedList() {
	}

	@java.lang.SuppressWarnings("all")
	public AnnotatedList(final List<AnnotatedItem<Item, IP>> data, final LP permissions, final Pagination pagination) {
		this.data = data;
		this.permissions = permissions;
		this.pagination = pagination;
	}
}
