// Generated by delombok at Tue Jul 03 21:08:31 NOVT 2018
package org.statesync.model;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import javax.validation.ConstraintViolation;
import javax.validation.Validator;
import javax.validation.groups.Default;
import org.statesync.model.permissions.FormPermissions;

public class AnnotatedForm<Item, Permissions extends FormPermissions> {
	public Item data;
	public Permissions permissions;
	public final Map<String, String> errors = new HashMap<>();
	public FormState state = FormState.edit;

	public void validate(final Validator validator) {
		final Set<ConstraintViolation<Item>> set = validator.validate(this.data, Default.class);
		this.errors.clear();
		for (final ConstraintViolation<Item> v : set) {
			final String propertyId = v.getPropertyPath().toString();
			String text = this.errors.get(propertyId);
			text = text == null ? v.getMessage() : text + ", " + v.getMessage();
			this.errors.put(propertyId, text);
		}
		this.permissions.update = this.errors.isEmpty();
	}

	@java.lang.SuppressWarnings("all")
	public Item getData() {
		return this.data;
	}

	@java.lang.SuppressWarnings("all")
	public Permissions getPermissions() {
		return this.permissions;
	}

	@java.lang.SuppressWarnings("all")
	public Map<String, String> getErrors() {
		return this.errors;
	}

	@java.lang.SuppressWarnings("all")
	public FormState getState() {
		return this.state;
	}

	@java.lang.SuppressWarnings("all")
	public void setData(final Item data) {
		this.data = data;
	}

	@java.lang.SuppressWarnings("all")
	public void setPermissions(final Permissions permissions) {
		this.permissions = permissions;
	}

	@java.lang.SuppressWarnings("all")
	public void setState(final FormState state) {
		this.state = state;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof AnnotatedForm)) return false;
		final AnnotatedForm<?, ?> other = (AnnotatedForm<?, ?>) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$data = this.getData();
		final java.lang.Object other$data = other.getData();
		if (this$data == null ? other$data != null : !this$data.equals(other$data)) return false;
		final java.lang.Object this$permissions = this.getPermissions();
		final java.lang.Object other$permissions = other.getPermissions();
		if (this$permissions == null ? other$permissions != null : !this$permissions.equals(other$permissions)) return false;
		final java.lang.Object this$errors = this.getErrors();
		final java.lang.Object other$errors = other.getErrors();
		if (this$errors == null ? other$errors != null : !this$errors.equals(other$errors)) return false;
		final java.lang.Object this$state = this.getState();
		final java.lang.Object other$state = other.getState();
		if (this$state == null ? other$state != null : !this$state.equals(other$state)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof AnnotatedForm;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $data = this.getData();
		result = result * PRIME + ($data == null ? 43 : $data.hashCode());
		final java.lang.Object $permissions = this.getPermissions();
		result = result * PRIME + ($permissions == null ? 43 : $permissions.hashCode());
		final java.lang.Object $errors = this.getErrors();
		result = result * PRIME + ($errors == null ? 43 : $errors.hashCode());
		final java.lang.Object $state = this.getState();
		result = result * PRIME + ($state == null ? 43 : $state.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "AnnotatedForm(data=" + this.getData() + ", permissions=" + this.getPermissions() + ", errors=" + this.getErrors() + ", state=" + this.getState() + ")";
	}

	@java.lang.SuppressWarnings("all")
	public AnnotatedForm(final Item data, final Permissions permissions, final FormState state) {
		this.data = data;
		this.permissions = permissions;
		this.state = state;
	}

	@java.lang.SuppressWarnings("all")
	public AnnotatedForm() {
	}
}
