// Generated by delombok at Tue Jul 03 21:08:31 NOVT 2018
package org.statesync.model;

import org.statesync.model.permissions.ItemPermissions;

public class AnnotatedItem<Item, Permissions extends ItemPermissions> {
	public Item data;
	public Permissions permissions;

	@java.lang.SuppressWarnings("all")
	public Item getData() {
		return this.data;
	}

	@java.lang.SuppressWarnings("all")
	public Permissions getPermissions() {
		return this.permissions;
	}

	@java.lang.SuppressWarnings("all")
	public void setData(final Item data) {
		this.data = data;
	}

	@java.lang.SuppressWarnings("all")
	public void setPermissions(final Permissions permissions) {
		this.permissions = permissions;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof AnnotatedItem)) return false;
		final AnnotatedItem<?, ?> other = (AnnotatedItem<?, ?>) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$data = this.getData();
		final java.lang.Object other$data = other.getData();
		if (this$data == null ? other$data != null : !this$data.equals(other$data)) return false;
		final java.lang.Object this$permissions = this.getPermissions();
		final java.lang.Object other$permissions = other.getPermissions();
		if (this$permissions == null ? other$permissions != null : !this$permissions.equals(other$permissions)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof AnnotatedItem;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $data = this.getData();
		result = result * PRIME + ($data == null ? 43 : $data.hashCode());
		final java.lang.Object $permissions = this.getPermissions();
		result = result * PRIME + ($permissions == null ? 43 : $permissions.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "AnnotatedItem(data=" + this.getData() + ", permissions=" + this.getPermissions() + ")";
	}

	@java.lang.SuppressWarnings("all")
	public AnnotatedItem(final Item data, final Permissions permissions) {
		this.data = data;
		this.permissions = permissions;
	}

	@java.lang.SuppressWarnings("all")
	public AnnotatedItem() {
	}
}
