// Generated by delombok at Tue Jul 03 21:08:31 NOVT 2018
package org.statesync.model;

public class ListQuery {
	public String search = "";
	public String sortBy;
	public String sortDirection;
	public int page;
	public int pageSize = 5;
	public String zoneId;

	public String[] searchKeywords() {
		return this.search == null ? new String[0] : this.search.split("\\s");
	}

	public void validate(final String defaultSearch) {
		if (this.pageSize < 5) this.pageSize = 5;
		if (this.page < 0) this.page = 0;
		if (this.sortBy == null) this.sortBy = defaultSearch;
		if (this.sortDirection == null) this.sortDirection = "asc";
	}

	@java.lang.SuppressWarnings("all")
	public ListQuery() {
	}

	@java.lang.SuppressWarnings("all")
	public String getSearch() {
		return this.search;
	}

	@java.lang.SuppressWarnings("all")
	public String getSortBy() {
		return this.sortBy;
	}

	@java.lang.SuppressWarnings("all")
	public String getSortDirection() {
		return this.sortDirection;
	}

	@java.lang.SuppressWarnings("all")
	public int getPage() {
		return this.page;
	}

	@java.lang.SuppressWarnings("all")
	public int getPageSize() {
		return this.pageSize;
	}

	@java.lang.SuppressWarnings("all")
	public String getZoneId() {
		return this.zoneId;
	}

	@java.lang.SuppressWarnings("all")
	public void setSearch(final String search) {
		this.search = search;
	}

	@java.lang.SuppressWarnings("all")
	public void setSortBy(final String sortBy) {
		this.sortBy = sortBy;
	}

	@java.lang.SuppressWarnings("all")
	public void setSortDirection(final String sortDirection) {
		this.sortDirection = sortDirection;
	}

	@java.lang.SuppressWarnings("all")
	public void setPage(final int page) {
		this.page = page;
	}

	@java.lang.SuppressWarnings("all")
	public void setPageSize(final int pageSize) {
		this.pageSize = pageSize;
	}

	@java.lang.SuppressWarnings("all")
	public void setZoneId(final String zoneId) {
		this.zoneId = zoneId;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof ListQuery)) return false;
		final ListQuery other = (ListQuery) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$search = this.getSearch();
		final java.lang.Object other$search = other.getSearch();
		if (this$search == null ? other$search != null : !this$search.equals(other$search)) return false;
		final java.lang.Object this$sortBy = this.getSortBy();
		final java.lang.Object other$sortBy = other.getSortBy();
		if (this$sortBy == null ? other$sortBy != null : !this$sortBy.equals(other$sortBy)) return false;
		final java.lang.Object this$sortDirection = this.getSortDirection();
		final java.lang.Object other$sortDirection = other.getSortDirection();
		if (this$sortDirection == null ? other$sortDirection != null : !this$sortDirection.equals(other$sortDirection)) return false;
		if (this.getPage() != other.getPage()) return false;
		if (this.getPageSize() != other.getPageSize()) return false;
		final java.lang.Object this$zoneId = this.getZoneId();
		final java.lang.Object other$zoneId = other.getZoneId();
		if (this$zoneId == null ? other$zoneId != null : !this$zoneId.equals(other$zoneId)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof ListQuery;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $search = this.getSearch();
		result = result * PRIME + ($search == null ? 43 : $search.hashCode());
		final java.lang.Object $sortBy = this.getSortBy();
		result = result * PRIME + ($sortBy == null ? 43 : $sortBy.hashCode());
		final java.lang.Object $sortDirection = this.getSortDirection();
		result = result * PRIME + ($sortDirection == null ? 43 : $sortDirection.hashCode());
		result = result * PRIME + this.getPage();
		result = result * PRIME + this.getPageSize();
		final java.lang.Object $zoneId = this.getZoneId();
		result = result * PRIME + ($zoneId == null ? 43 : $zoneId.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "ListQuery(search=" + this.getSearch() + ", sortBy=" + this.getSortBy() + ", sortDirection=" + this.getSortDirection() + ", page=" + this.getPage() + ", pageSize=" + this.getPageSize() + ", zoneId=" + this.getZoneId() + ")";
	}
}
