// Generated by delombok at Tue Jul 03 21:08:31 NOVT 2018
package org.statesync.model;

public class PaginationItem {
	public PaginationItemType type;
	public int page;
	public boolean disabled;
	public String label;
	public String badge;

	@java.lang.SuppressWarnings("all")
	public PaginationItemType getType() {
		return this.type;
	}

	@java.lang.SuppressWarnings("all")
	public int getPage() {
		return this.page;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isDisabled() {
		return this.disabled;
	}

	@java.lang.SuppressWarnings("all")
	public String getLabel() {
		return this.label;
	}

	@java.lang.SuppressWarnings("all")
	public String getBadge() {
		return this.badge;
	}

	@java.lang.SuppressWarnings("all")
	public void setType(final PaginationItemType type) {
		this.type = type;
	}

	@java.lang.SuppressWarnings("all")
	public void setPage(final int page) {
		this.page = page;
	}

	@java.lang.SuppressWarnings("all")
	public void setDisabled(final boolean disabled) {
		this.disabled = disabled;
	}

	@java.lang.SuppressWarnings("all")
	public void setLabel(final String label) {
		this.label = label;
	}

	@java.lang.SuppressWarnings("all")
	public void setBadge(final String badge) {
		this.badge = badge;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof PaginationItem)) return false;
		final PaginationItem other = (PaginationItem) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$type = this.getType();
		final java.lang.Object other$type = other.getType();
		if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
		if (this.getPage() != other.getPage()) return false;
		if (this.isDisabled() != other.isDisabled()) return false;
		final java.lang.Object this$label = this.getLabel();
		final java.lang.Object other$label = other.getLabel();
		if (this$label == null ? other$label != null : !this$label.equals(other$label)) return false;
		final java.lang.Object this$badge = this.getBadge();
		final java.lang.Object other$badge = other.getBadge();
		if (this$badge == null ? other$badge != null : !this$badge.equals(other$badge)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof PaginationItem;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $type = this.getType();
		result = result * PRIME + ($type == null ? 43 : $type.hashCode());
		result = result * PRIME + this.getPage();
		result = result * PRIME + (this.isDisabled() ? 79 : 97);
		final java.lang.Object $label = this.getLabel();
		result = result * PRIME + ($label == null ? 43 : $label.hashCode());
		final java.lang.Object $badge = this.getBadge();
		result = result * PRIME + ($badge == null ? 43 : $badge.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "PaginationItem(type=" + this.getType() + ", page=" + this.getPage() + ", disabled=" + this.isDisabled() + ", label=" + this.getLabel() + ", badge=" + this.getBadge() + ")";
	}

	@java.lang.SuppressWarnings("all")
	public PaginationItem(final PaginationItemType type, final int page, final boolean disabled, final String label, final String badge) {
		this.type = type;
		this.page = page;
		this.disabled = disabled;
		this.label = label;
		this.badge = badge;
	}
}
