// Generated by delombok at Tue Jul 03 21:08:31 NOVT 2018
package org.statesync.model.permissions;

/**
 * @author ify
 */
public class FormPermissions implements ItemPermissions {
	/**
	 * Data is ready to be updated on server side. Usually used to disable
	 * submit button on client
	 */
	public boolean update;

	@java.lang.SuppressWarnings("all")
	public FormPermissions() {
	}

	/**
	 * Data is ready to be updated on server side. Usually used to disable
	 * submit button on client
	 */
	@java.lang.SuppressWarnings("all")
	public boolean isUpdate() {
		return this.update;
	}

	/**
	 * Data is ready to be updated on server side. Usually used to disable
	 * submit button on client
	 */
	@java.lang.SuppressWarnings("all")
	public void setUpdate(final boolean update) {
		this.update = update;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof FormPermissions)) return false;
		final FormPermissions other = (FormPermissions) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (this.isUpdate() != other.isUpdate()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof FormPermissions;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + (this.isUpdate() ? 79 : 97);
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "FormPermissions(update=" + this.isUpdate() + ")";
	}
}
