// Generated by delombok at Tue Jul 03 21:08:31 NOVT 2018
package org.statesync.model.permissions;

public class ItemCrudPermissions implements ItemPermissions {
	public boolean edit;
	public boolean delete;

	@java.lang.SuppressWarnings("all")
	public ItemCrudPermissions() {
	}

	@java.lang.SuppressWarnings("all")
	public boolean isEdit() {
		return this.edit;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isDelete() {
		return this.delete;
	}

	@java.lang.SuppressWarnings("all")
	public void setEdit(final boolean edit) {
		this.edit = edit;
	}

	@java.lang.SuppressWarnings("all")
	public void setDelete(final boolean delete) {
		this.delete = delete;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof ItemCrudPermissions)) return false;
		final ItemCrudPermissions other = (ItemCrudPermissions) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (this.isEdit() != other.isEdit()) return false;
		if (this.isDelete() != other.isDelete()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof ItemCrudPermissions;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + (this.isEdit() ? 79 : 97);
		result = result * PRIME + (this.isDelete() ? 79 : 97);
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "ItemCrudPermissions(edit=" + this.isEdit() + ", delete=" + this.isDelete() + ")";
	}
}
