// Generated by delombok at Tue Jul 03 21:08:31 NOVT 2018
package org.statesync.model.permissions;

public class ListCrudPermissions implements ListPermissions {
	public boolean create;
	public boolean delete;

	@java.lang.SuppressWarnings("all")
	public ListCrudPermissions() {
	}

	@java.lang.SuppressWarnings("all")
	public boolean isCreate() {
		return this.create;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isDelete() {
		return this.delete;
	}

	@java.lang.SuppressWarnings("all")
	public void setCreate(final boolean create) {
		this.create = create;
	}

	@java.lang.SuppressWarnings("all")
	public void setDelete(final boolean delete) {
		this.delete = delete;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof ListCrudPermissions)) return false;
		final ListCrudPermissions other = (ListCrudPermissions) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (this.isCreate() != other.isCreate()) return false;
		if (this.isDelete() != other.isDelete()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof ListCrudPermissions;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + (this.isCreate() ? 79 : 97);
		result = result * PRIME + (this.isDelete() ? 79 : 97);
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "ListCrudPermissions(create=" + this.isCreate() + ", delete=" + this.isDelete() + ")";
	}
}
